import { QA } from './qa';
import { readQaParams } from './params-qa';

export const params: ReturnType<typeof readQaParams> = QA ? readQaParams() : {
  shot: false,
  debug: '',
  ratio: null,
  cam: null,
  sun: null,
  grass: null,
  msaa: null,
  dusk: null,
  shower: null,
  fog: null,
  villageFog: true,
  villageMist: false,
  storm: null,
  chapter: null,
  progress: true,
  lite: false,
  mirror: null,
  mirrorlod: 'coarse',
  blades: 'table',
  heights: 'atlas',
  grasslod: null,
  hold: null,
  stats: false,
  whale: false,
  lines: false,
  coldshaders: false,
};
